#!/bin/bash

# VARIABLES
mensaje="¡Hola, bienvenido al script de David!"

# PARÁMETROS
echo "El nombre del script es: $0"
echo "El primer parámetro es: $1"
echo "El segundo parámetro es: $2"

# VARIABLES ESPECIALES
echo "El número total de parámetros es: $#"
echo "Todos los parámetros como una sola palabra: $*"
echo "Todos los parámetros como una lista: $@"

# COMANDO READ
read -p "Introduce tu nombre: " nombre
echo "Hola, $nombre"

# EXPRESIÓN ARITMÉTICA
read -p "Introduce un número: " num1
read -p "Introduce otro número: " num2
suma=$((num1 + num2))
echo "La suma de $num1 y $num2 es: $suma"




